### ISSUE TITLE
我想爬排行榜的壁纸，但是爬取的图片不对

### ISSUE THREAD

**Issue by a86490551** [1343890272/img-spider#2]
排行榜我分类好一共有102页，一页24张壁纸。
但是爬出来只有300多张壁纸，这是怎么回事呢？

**Comment by a86490551** [comment]
还有经常爬到90%多会卡住。

**Comment by 1343890272** [comment]
> 排行榜我分类好一共有102页，一页24张壁纸。
> 但是爬出来只有300多张壁纸，这是怎么回事呢？
爬太快限制了，状态码429，加个判断就能解决

**Comment by 1343890272** [comment]
> 还有经常爬到90%多会卡住。

可能有几张卡住了，加个超时重试就行
